site:
  url: "https://chrisding.xyz"
  name: "Chris's blog"
  author: "Chris"
  locale: "en"
  keywords:
    - Blog
    - Chris
  description: "Chris's blog."
  social:
    x: "https://x.com/chris1ding1"
    instagram: ""
    github: "https://github.com/chris1ding1"
    linkedin: ""

paths:
  content: "content"
  output: "dist"
  public: "public"
  drafts: "draft"

projects:
  - name: "WishWell"
    description: "May you be free."
    link: "https://wishwell.life/"
    icon: "https://wishwell.life/favicons/favicon.svg"
  - name: "1024 Developer Platform"
    description: "Tech-related sharing and discussions, developer tools and data report."
    link: "https://1024.dev/"
    icon: "https://1024.dev/favicon.svg"
  - name: "Txtify"
    description: "A handy text processing assistant with practical features including character counting, case conversion, and singular/plural transformation - making text processing simpler and more efficient."
    link: "https://txtify.app"
    icon: "https://txtify.app/favicon.svg"
