site:
  url: "https://chrisding.xyz"
  name: "Chris's blog"
  author: "Chris"
  locale: "en"
  keywords:
    - Blog
    - Chris
  description: "Chris's blog."
  social:
    x: "https://x.com/chris1ding1"
    instagram: ""
    github: "https://github.com/chris1ding1"
    linkedin: ""

paths:
  content: "content"
  output: "dist"
  public: "public"

projects:
  - name: "WishWell"
    description: "May you be free."
    link: "https://wishwell.life/"
    icon: "https://wishwell.life/favicons/favicon.svg"
