site:
  url: "https://chrisding.xyz"
  name: "Chris's blog"
  alternate_name:
  author: "Chris"
  locale: "en"
  time_zone: "UTC"
  keywords:
    - Blog
    - Chris
  description: "Chris's blog."
  sort_by: "created"
  article_type: "BlogPosting"
  about:
    type: Person
    name: "Chris"
    alternate_name: ""
    description: ""
    same_as:
      - "https://x.com/chris1ding1"
      - "https://github.com/chris1ding1"
      - "https://bento.me/chrisding"
  socials:
    x: "chris1ding1"
    instagram: ""
    github: "https://github.com/chris1ding1"
    linkedin: ""

paths:
  content: "content"
  output: "dist"
  public: "public"
  drafts: "drafts"

projects:
  - name: "WishWell"
    description: "May you be free."
    link: "https://wishwell.life/"
    icon: "https://wishwell.life/favicons/favicon.svg"
  - name: "1024 Developer Platform"
    description: "Tech-related sharing and discussions, developer tools and data report."
    link: "https://1024.dev/"
    icon: "https://1024.dev/favicon.svg"
  - name: "Txtify"
    description: "A handy text processing assistant with practical features including character counting, case conversion, and singular/plural transformation - making text processing simpler and more efficient."
    link: "https://txtify.app"
    icon: "https://txtify.app/favicon.svg"
