site:
  url: "https://chrisding.xyz"
  name: "Chris's blog"
  alternate_name:
  author: "Chris"
  locale: "en"
  time_zone: "UTC"
  keywords:
    - Blog
    - Chris
  description: "Chris's blog. 生活记录和技术笔记。"
  sort_by: "created"
  article_type: "BlogPosting"
  about:
    type: Person
    name: "Chris"
    alternate_name: ""
    description: "I'm Chris. 多数时间是一名软件开发者，也曾有过一段创业经历（中国和欧洲）。注重守时。从 2016 年左右，可能更早，对于需付费的软件，一直正版订阅。每当在微信朋友圈看到大病众筹的信息，基本都会捐款，略表心意，看到喜欢或者认为有价值的公众号文章大概率的会赞赏（这几年少了，因为很少看公众号文章了以及朋友圈发众筹的少了）。有一点点对开源作者和正义的支持。"
    same_as:
      - "https://x.com/chrisdingxyz"
      - "https://github.com/chris1ding1"
      - "https://bento.me/chrisding"
  socials:
    x: "chrisdingxyz"
    instagram: ""
    github: "https://github.com/chris1ding1"
    linkedin: ""
    pinterest: "https://www.pinterest.com/chris1ding1/_created"

paths:
  content: "content"
  output: "dist"
  public: "public"
  drafts: "drafts"

projects:
  - name: "1024 Developer Platform"
    description: "Tech-related sharing and discussions, developer tools and data report."
    link: "https://1024.dev/"
    icon: "https://1024.dev/favicon.svg"
  - name: "Pin Hub - Bookmark Manager"
    description: "Easily save your favorite URLs, images, notes, and voice memos."
    link: "https://pinhub.xyz"
    icon: "https://pinhub.xyz/favicon.svg"
  - name: "Time Mate - Your Time Companion"
    description: "Calendar, Current Time, Durations, Milestone & Timelines."
    link: "https://timemate.app"
    icon: "https://timemate.app/favicons/favicon.svg"
  - name: "Txtify - Text Helper"
    description: "A handy text processing assistant with practical features including character counting, case conversion, and singular/plural transformation - making text processing simpler and more efficient."
    link: "https://txtify.app"
    icon: "https://txtify.app/favicon.svg"
